---
# handlers file for promtail role

- name: restart promtail docker compose
  community.docker.docker_compose_v2:
    project_src: '{{ promtail_path }}'
    services:
      - promtail
    state: restarted
  listen: restart promtail
  when: promtail_deploy_mode == 'docker'

- name: restart promtail service
  service:
    name: promtail
    enabled: true
    state: restarted
  listen: restart promtail
  when: promtail_deploy_mode == 'binary'

- name: promtail_daemon_reload_systemd
  become: true
  systemd:
    daemon_reload: true
