## Manage properties of a zfs zpool
## inner tasks file, included by loop in main.yml

- name: print zpool facts for {{ zpool }}
  debug:
    var: zfs_zpool__zpool_facts
  # changed_when: true

- name: set zfs dataset properties for {{ zpool }}
  zfs:
    name: "{{ zpool }}"
    state: present
    extra_zfs_properties: '{{ zfs_zpool_properties }}'

- name: zpool set autotrim=on {{ zpool }} # noqa no-changed-when
  command: /usr/sbin/zpool set autotrim=on {{ zpool }}
  when:
    - zfs_zpool__zpool_facts.autotrim == "off"
    - zfs_zpool_autotrim

- name: zpool set autotrim=off {{ zpool }} # noqa no-changed-when
  command: /usr/sbin/zpool set autotrim=off {{ zpool }}
  when:
    - zfs_zpool__zpool_facts.autotrim == "on"
    - not zfs_zpool_autotrim
