---
- name: Copy VMagent systemd unit file
  template:
    src: vmagent.service.j2
    dest: /etc/systemd/system/vic-vmagent.service
    owner: root
    group: root
    mode: '0644'
  no_log: true
  notify:
    - vmagent-daemon-reload
    - vmagent-restart

- name: Ensure VMagent service is enabled on boot
  become: true
  systemd:
    name: vic-vmagent
    enabled: true

- name: Prepare configuration dir
  file:
    state: directory
    path: "{{ vmagent_config_dir }}"
    mode: '0751'
    owner: "{{ vmagent_system_user }}"
    group: "{{ vmagent_system_group }}"

- name: Prepare scrape_configs dir
  file:
    state: directory
    path: "{{ vmagent_scrape_config_dir }}"
    mode: '0751'
    owner: "{{ vmagent_system_user }}"
    group: "{{ vmagent_system_group }}"

- name: Prepare sd configuration dir
  file:
    state: directory
    path: "{{ vmagent_sd_config_dir }}"
    mode: '0777'
    owner: "{{ vmagent_system_user }}"
    group: "{{ vmagent_system_group }}"

- name: create file discovery configuration
  copy:
    content: |
      #
      # Managed by ansible
      #
      {{ item.config | to_nice_yaml(indent=2) }}
    dest: "{{ vmagent_sd_config_dir }}/{{ item.name | default('custom') }}.{{ item.job }}.yml"
    owner: "{{ vmagent_system_user }}"
    group: "{{ vmagent_system_group }}"
    mode: '0640'
  loop: '{{ vmagent_file_sd_config }}'

- name: Configure promscrape config
  template:
    src: prometheus_scrape.yml.j2
    dest: "{{ vmagent_config_dir }}/config.yml"
    mode: '0640'
    owner: "{{ vmagent_system_user }}"
    group: "{{ vmagent_system_group }}"
    validate: /usr/local/bin/vmagent-prod -dryRun -promscrape.config %s
  notify: vmagent-reload

- name: always validate config
  command: /usr/local/bin/vmagent-prod -dryRun -promscrape.config "{{ vmagent_config_dir }}/config.yml"
  changed_when: false
