---
# Path where the docker-compose file will be stored
smee_path: '/container/smee'

# Domain configuration
smee_domain: 'smee.{{ ansible_fqdn }}'
smee_addon_domains: []
smee_domains: '{{ [smee_domain] + smee_addon_domains }}'

# Gosmee configuration
smee_gosmee_version: 'latest'
smee_image: 'ghcr.io/chmouel/gosmee'

# Security settings
smee_webhook_signatures: []  # List of secrets for webhook signature validation
smee_allowed_ips: []         # List of allowed IPs/CIDR ranges for webhook POST requests, check README.md for Examples.

# Docker configuration
smee_docker_pull: '{{ global_docker_pull | default(False) }}'
