# regenerates nginx conf from templates
# this is not the same as just reloading the config
- name: restart nginx config generator of webproxy
  community.docker.docker_compose_v2:
    project_src: '{{ oauth2_proxy_webproxy_path }}'
    services:
      - 'docker-gen'
      - 'nginx'
    state: restarted
  listen:
    - oauth2_proxy_regenerate_webproxy_config
  tags: compose_up
