---
- name: restart zfs_exporter
  service:
    name: zfs_exporter
    state: restarted

- name: zfs_exporter_metrics_scraper_service_reload # noqa ignore-errors
  service:
    name: '{{ zfs_exporter_metrics_scraper_service }}'
    state: reloaded
  ignore_errors: true # ignore error if vmagent is not yet set up
