---
- name: webserver_restart
  community.docker.docker_compose_v2:
    project_src: '{{ webserver_path }}'
    state: restarted
  tags: compose_up

- name: webserver_restart_nginx
  community.docker.docker_compose_v2:
    project_src: '{{ webserver_path }}'
    services:
      - web
    state: restarted
  tags: compose_up

- name: webserver_restart_php
  community.docker.docker_compose_v2:
    project_src: '{{ webserver_path }}'
    services:
      - php
    build: 'always'
    state: restarted
  tags: compose_up

- name: webserver_recreate_sftp
  community.docker.docker_compose_v2:
    project_src: '{{ webserver_path }}'
    services:
      - sftp
    state: restarted
  tags: compose_up
