# Hetzner Robot Setup

- name: remove ssh hostkey (before connecting to rescue system) # noqa no-changed-when
  delegate_to: localhost
  command: ssh-keygen -R '{{ item }}'
  check_mode: false
  with_items:
    - '{{ ansible_host }}'
    - '{{ inventory_hostname }}'

- name: gather_facts
  gather_facts: {}

- name: check if connected to rescue system
  stat:
    path: /root/.oldroot/nfs/
  register: hetzner_robot_reg__stat_oldroot
  tags:
    - always

# - assert:
#     that:  hetzner_robot_reg__stat_oldroot.stat.exists
#     fail_msg: "Not a Hetzner Rescue system"

- name: rescue system block
  when: hetzner_robot_reg__stat_oldroot.stat.exists
  block:
    - name: copy install scripts to writable path
      ansible.posix.synchronize:
        src: /root/.oldroot/nfs/install/
        dest: /root/install/
      delegate_to: "{{ inventory_hostname }}"

    - name: Hack to force GPT Layout
      ansible.builtin.lineinfile:
        path: /root/install/functions.sh
        regexp: '^  FORCE_GPT='
        line: '  FORCE_GPT="2"'
      when: hetzner_robot_force_gpt

    - name: print hetzner_robot_installimage_command
      debug:
        var: hetzner_robot_installimage_command
      changed_when: true

    - name: prompt before continue
      pause:
        prompt: |
          Please confirm the installation procedure of "{{ inventory_hostname }}"

          Enter "yes" to continue. Press ENTER to exit now.
      register: hetzner_robot_reg__prompt_install

    - name: Cancel if not confirmed
      fail:
        msg: "Exit now"
      when:
        - hetzner_robot_reg__prompt_install.user_input != "yes"

    - name: installimage # noqa no-changed-when command-instead-of-shell
      shell: '{{ hetzner_robot_installimage_command }}'
      environment:
        TERM: xterm

    - name: stop md raid # noqa no-changed-when
      command: "mdadm --manage --stop {{ item }}"
      with_items: "{{ hetzner_robot_stop_mdraid }}"
      tags:
        - mdadm_stop

    - name: remove md raid superblock # noqa no-changed-when
      command: "mdadm --misc --zero-superblock {{ item }}"
      with_items: "{{ hetzner_robot_clear_mdraid_partitions }}"
      tags:
        - mdadm_remove

    - name: remove ssh hostkey # noqa no-changed-when
      delegate_to: localhost
      command: ssh-keygen -R '{{ item }}'
      with_items:
        - '{{ ansible_host }}'
        - '{{ inventory_hostname }}'

    - name: reboot to installed system
      reboot:
        post_reboot_delay: 30 # wait after reboot to allow system to be fully ready

    - name: new facts after reboot
      gather_facts: {}

- name: check that fqdn is correct
  assert:
    that: ansible_fqdn == inventory_hostname

- name: ensure apt list dir exists
  file:
    path: /var/lib/apt/lists/
    state: directory
    mode: '0755'

# Sometimes apt tasks fail because apt is locked by an autoupdate or by a race condition on a thread.
# To check for a lock file before executing, and keep trying until the lock file is released:
- name: update apt list
  apt:
    update_cache: true
  register: hetzner_robot_reg__apt_update_cache
  retries: 10
  delay: 5
  until: hetzner_robot_reg__apt_update_cache is success or ('Failed to lock apt for exclusive operation' not in hetzner_robot_reg__apt_update_cache.msg and '/var/lib/dpkg/lock' not in hetzner_robot_reg__apt_update_cache.msg)

- name: install zfs tools
  apt:
    name: zfsutils-linux
    state: present

- name: create zpool zfsdata
  command: "zpool create zfsdata mirror {{ hetzner_robot_zfsdata_partitions_by_id | join(' ') }} -o ashift=12 -O compression=lz4"
  register: hetzner_robot_reg__create_zfsdata
  args:
    creates: /zfsdata

# extend pool with more vdevs (for mirror: extend by pairs of 2 devices)
- name: extend zpool zfsdata # noqa no-handler no-changed-when
  command: "zpool add zfsdata mirror {{ item | join(' ') }} -o ashift=12"
  loop: '{{ hetzner_robot_zfsdata_extend_groups }}'
  when:
    - hetzner_robot_reg__create_zfsdata.changed

- name: create zpool zfsbulk # noqa no-changed-when
  command: "zpool create zfsbulk {{ hetzner_robot_zfsbulk_pool_type }} {{ hetzner_robot_zfsbulk_partitions_by_id | join(' ') }} -o ashift=12 -O compression=lz4"
  args:
    creates: /zfsbulk
  register: hetzner_robot_reg__create_zfsbulk
  when: hetzner_robot_zfsbulk

# extend pool with more vdevs (for mirror: extend by pairs of 2 devices)
- name: extend zpool zfsbulk # noqa no-changed-when no-handler
  command: "zpool add zfsbulk {{ hetzner_robot_zfsbulk_pool_type }} {{ item | join(' ') }} -o ashift=12"
  loop: '{{ hetzner_robot_zfsbulk_extend_groups }}'
  when:
    - hetzner_robot_zfsbulk
    - hetzner_robot_reg__create_zfsbulk.changed

- name: zfsbulk add cache devices # noqa no-changed-when no-handler
  command: "zpool add zfsbulk cache {{ hetzner_robot_zfsbulk_cache_partitions_by_id | join(' ') }} -o ashift=12"
  when:
    - hetzner_robot_zfsbulk
    - hetzner_robot_zfsbulk_cache
    - hetzner_robot_reg__create_zfsbulk.changed

- name: create zfs write intent log file # noqa no-changed-when no-handler
  command: dd if=/dev/zero of=/zfs_log_file bs=1M count=4000
  args:
    creates: /zfs_log_file
  register: hetzner_robot_reg__zfsbulk_log_file
  when:
    - hetzner_robot_zfsbulk
    - hetzner_robot_zfsbulk_log_file

- name: add zfs write intent log # noqa no-changed-when no-handler
  command: zpool add zfsbulk log {{ hetzner_robot_zfsbulk_log_device }}
  when:
    - hetzner_robot_zfsbulk
    - hetzner_robot_reg__create_zfsbulk.changed
    - hetzner_robot_zfsbulk_log_device

- name: collect zpool facts
  zpool_facts: {}
  register: hetzner_robot_reg__zpool_facts

- name: print zpool facts
  debug:
    var: hetzner_robot_reg__zpool_facts

- name: set zfs dataset properties for zfsdata
  zfs:
    name: zfsdata
    state: present
    extra_zfs_properties:
      atime: 'on'
      relatime: 'on'
      # snapdir: visible
      xattr: sa
      acltype: posix

- name: set zfs dataset properties for zfsbulk
  zfs:
    name: zfsbulk
    state: present
    extra_zfs_properties:
      atime: 'on'
      relatime: 'on'
      # snapdir: visible
      xattr: sa
      acltype: posix
  when:
    - hetzner_robot_zfsbulk

- name: create zfs volume for docker
  zfs:
    name: zfsdata/docker
    state: present
    extra_zfs_properties:
      mountpoint: /var/lib/docker

- name: create zfs volume
  zfs:
    name: zfsdata/container
    state: present
    extra_zfs_properties:
      mountpoint: /container

# - name: create zfsbulk /data volume
#   zfs:
#     name: zfsbulk/data
#     state: present
#     extra_zfs_properties:
#       mountpoint: /data
#       relatime: 'on'

# - name: create zfs volume test
#   zfs:
#     name: zfsdata/container/test
#     state: present
#     extra_zfs_properties:
#       mountpoint: /container/test
#       relatime: 'on'
#   tags: zfstest

# - name: set zfs dataset properties for zfsdata
#   zfs:
#     name: zfsdata
#     state: present
#     extra_zfs_properties:
#       relatime: 'on'
#   tags: zfstest
