---
- name: create promtail system group
  group:
    name: promtail
    system: true
    state: present

- name: create promtail system user
  user:
    name: promtail
    system: true
    shell: "/sbin/nologin"
    group: promtail
    groups: "{{ promtail_additional_groups | default('systemd-journal') }}"
    createhome: false

- name: create promtail directories
  file:
    path: "{{ item }}"
    state: directory
    owner: promtail
    group: promtail
    mode: '0750'
  with_items:
    - "{{ promtail_config_dir }}"
    - /var/log/promtail/

- name: Promtail Configuration File
  template:
    src: promtail-config.yml.j2
    dest: '{{ promtail_config_dir }}/promtail.yml'
    owner: promtail
    group: promtail
    mode: '0640'
  notify: restart promtail

- name: Create download directory
  delegate_to: localhost
  file:
    path: "{{ promtail_local_cache_dir }}/promtail-{{ promtail_version }}"
    state: directory
    mode: '0755'
  check_mode: false

- name: download promtail version {{ promtail_version }} # noqa risky-file-permissions
  delegate_to: localhost
  become: false
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/{{ item.name }}.zip"
    dest: "{{ promtail_local_cache_dir }}/promtail-{{ promtail_version }}/{{ item.name }}.zip"
    checksum: "sha256:{{ item.checksum }}"
  register: promtail_reg__download_archive
  until: promtail_reg__download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false
  with_items:
    - { name: promtail-linux-amd64, checksum: "{{ promtail_checksum }}" }

- name: unpack promtail binaries # noqa risky-file-permissions
  delegate_to: localhost
  become: false
  unarchive:
    remote_src: true
    src: "{{ promtail_local_cache_dir }}/promtail-{{ promtail_version }}/{{ item }}.zip"
    dest: "{{ promtail_local_cache_dir }}/promtail-{{ promtail_version }}"
    creates: "{{ promtail_local_cache_dir }}/promtail-{{ promtail_version }}/{{ item }}"
  check_mode: false
  with_items:
    - promtail-linux-amd64

- name: copy promtail-{{ promtail_version }}
  copy:
    remote_src: false
    src: "{{ promtail_local_cache_dir }}/promtail-{{ promtail_version }}/promtail-linux-amd64"
    dest: "/usr/local/bin/promtail"
    mode: '0755'
    owner: root
    group: root
  notify:
    - restart promtail

- name: create systemd service unit
  template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - promtail_daemon_reload_systemd
    - restart promtail

- name: Enable service promtail
  service:
    name: promtail
    enabled: true
