- name: create directories for promtail
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - '{{ promtail_path }}'
    - '{{ promtail_path }}/data'
    - '{{ promtail_path }}/data/promtail'

- name: Promtail Configuration File
  template:
    src: promtail-config.yml.j2
    dest: '{{ promtail_path }}/promtail-config.yml'
    owner: root
    group: root
    mode: '0640'
  notify: restart promtail

- name: healthcheck script
  template:
    src: healthcheck.sh
    dest: '{{ promtail_path }}/healthcheck.sh'
    owner: root
    group: root
    mode: '0750'
  notify: restart promtail

- name: deploy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: '{{ promtail_path }}/docker-compose.yml'
    owner: root
    group: root
    mode: '0640'

- name: promtail_docker-compose-up
  community.docker.docker_compose_v2:
    project_src: '{{ promtail_path }}'
    state: present
    pull: "{{ promtail_docker_pull | ternary('always', 'policy') }}"
  register: promtail__register_compose
  tags: compose_up

- name: print actions by compose # noqa no-handler
  vars:
    actions: "{{ promtail__register_compose.actions }}"
  debug:
    var: actions
  changed_when: true
  when: promtail__register_compose is defined and promtail__register_compose.changed
