---

# use compose to send a SIGHUP to blacbox's process (PID=1)
- name: dependabot reload # noqa no-changed-when
  command: 'docker compose exec -T dependabot kill -HUP 1'
  args:
    chdir: '{{ dependabot_path }}'

# regenerates nginx conf from templates
# this is not the same as just reloading the config
- name: restart nginx config generator of webproxy
  community.docker.docker_compose_v2:
    project_src: '{{ dependabot_webproxy_path }}'
    services:
      - 'docker-gen'
      - 'nginx'
    state: restarted
  listen:
    - dependabot_regenerate_webproxy_config
  tags: compose_up

...
