- name: deploy scrape config for vmagent
  template:
    src: canary_metrics_job.yml.j2
    dest: '{{ loki_canary_vmagent_scrape_config_dir }}/loki_canary.yml'
    owner: root
    group: root
    mode: '0644'
  notify: loki-canary-vmagent-reload
