#
# Managed by Ansible
#
groups:
  - name: system down
    rules:
      - alert: InstanceDown
        expr: 'up{job="netdata"} == 0'
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Host down: {{ $labels.host }}"
          description: "{{ $labels.host }} of job {{ $labels.job }} has been down for more than 5 minutes."

      # https://www.robustperception.io/alerting-on-gauges-in-prometheus-2-0
      - alert: InstanceDownAVG
        expr: 'avg_over_time(up{job="netdata"} [5m]) <= 0.9'
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host down: {{ $labels.host }}"
          description: "{{ $labels.host }} of job {{ $labels.job }} has been down for more than 5 minutes."

      # critical for job netdata if not reported up for 2 min.
      - alert: HostLastUpdate
        expr: time()-tlast_over_time(up{job="netdata"}[7d]) > 60*2
        # for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Host not reported up"
          description: The host {{ $labels.host }} last reported 'up' {{ $value | humanizeDuration }} ago

      # generic, warning only if no update for 5 min
      - alert: HostLastUpdate
        expr: time()-tlast_over_time(up{job!="netdata"}[7d]) > 60*5
        # for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Target not reported up for job {{ $labels.job }}"
          description: The job {{ $labels.job }} host {{ $labels.host }}, instance {{ $labels.instance }} last reported 'up' {{ $value | humanizeDuration }} ago

      - alert: HostNotUp
        expr: |
          count(up{host!=""} offset 60m) by (host,instance,job,scraper_instance)
          unless count(up{host!=""}) by (host,instance,job,scraper_instance)
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host Down? up metric missing"
          description: |-
            Host shut down or target removed? Missing updates for metric 'up' of host '{{ $labels.host }}', job: '{{ $labels.job }}'
            instance: '{{ $labels.instance }}', scraper: '{{ $labels.scraper_instance }}'
            The up metric has no current value but was available an hour ago.

  - name: cpu
    rules:
      - alert: HighCPU
        expr: 'sum(netdata_system_cpu_percentage_average{dimension!~"idle"}) by (host) > 80'
        for: 4m
        labels:
          severity: warning
        annotations:
          summary: "High CPU on {{ $labels.host }}"
          description: "{{ $labels.host }} CPU usage was above 80 for more than 4 minutes"

  - name: filesystem
    rules:
      - alert: DiskUsagePercentage
        expr: |
          (
            sum by (host, family)(netdata_disk_space_GiB_average{dimension="used", family!~"/boot/efi|/dev/shm|/run|/dev|/run/lock|/var/lib/lxd.*"})
            /
            sum by (host, family)(netdata_disk_space_GiB_average{})
          )
          * 100
          > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Disk Full on {{ $labels.host }}"
          description: "{{ $labels.host }}:{{ $labels.family }} filesystem with usage above 90% for longer than 5 minutes "

      - alert: MdRaidDiskFailed
        expr: 'netdata_md_health_failed_disks_average > 0'
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Mdraid failed disk on {{ $labels.host }}"
          description: "Mdraid failed disk on {{ $labels.host }} {{ $labels.dimension }} "


  - name: filesystemPrediction
    rules:
      - alert: DiskSpacePrediction36h
        expr: |
          predict_linear(
            netdata_disk_space_GiB_average{dimension="avail", family!~"/boot/efi|/dev/shm|/run|/dev|/run/.*|/var/lib/lxd.*"}
            [36h], 3600 * 36
            )
          < 5
          # filter out small partitions
          AND on(host,family) (
            sum by(host,family) (netdata_disk_space_GiB_average{}) > 20
          )
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "36h Disk space prediction low on {{ $labels.host }}"
          description: "Diskspace is predicted to get below 5GiB on host {{ $labels.host }} for mountpoint {{ $labels.family }}, prediction based on the last 36h"

      - alert: DiskSpacePrediction72h
        expr: |
          predict_linear(
            netdata_disk_space_GiB_average{dimension="avail", family!~"/boot/efi|/dev/shm|/run|/dev|/run/.*|/var/lib/lxd.*"}
            [36h], 3600 * 72
            )
          < 5
          # filter out small partitions
          AND on(host,family) (
            sum by(host,family) (netdata_disk_space_GiB_average{}) > 20
          )
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "72h Disk space prediction low  on {{ $labels.host }}"
          description: "Diskspace is predicted to get below 5GiB on host {{ $labels.host }} for mountpoint {{ $labels.family }}, prediction based on the last 36h"

      - alert: DiskInodesPrediction72h
        expr: |
          predict_linear(
            netdata_disk_inodes_inodes_average{dimension="avail", filesystem!="zfs", family!~"/boot/efi|/dev/shm|/run|/dev|/run/.*|/var/lib/lxd.*"}
            [36h], 3600 * 72
            )
          < 20000
          # filter out small partitions
          AND on(host,family) (
            sum by(host,family) (netdata_disk_space_GiB_average{}) > 20
          )
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "72h Inodes prediction low {{ $labels.host }}"
          description: "Inodes is predicted to get below 20'000 on host {{ $labels.host }} for mountpoint {{ $labels.family }}, prediction based on the last 36h"

  - name: ram
    rules:
      - alert: LowMemoryAvailable
        expr: |
          sum by (host)(netdata_mem_available_MiB_average)
          /
          sum by (host)(netdata_system_ram_MiB_average)
          *100
          < 5
          and
          (sum by (host)(netdata_mem_available_MiB_average) < 12000)
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low Mem available on host {{ $labels.host }}"
          description: "{{ $labels.host }} available RAM was below 5% for more than 5 minutes"

      - alert: CriticalLowMemoryAvailable
        expr: |
          sum by (host)(netdata_mem_available_MiB_average)
          /
          sum by (host)(netdata_system_ram_MiB_average)
          *100
          < 4
          and
          (sum by (host)(netdata_mem_available_MiB_average) < 6000)
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Very Low Mem available on host {{ $labels.host }}"
          description: "{{ $labels.host }} available RAM was below 4% for more than 5 minutes"

  # - name:
  #   rules:
  #   - alert:
  #     expr: ' > 80'
  #     for: 2m
  #     annotations:
  #       summary: "{{ $labels.host }}"
  #       description: "{{ $labels.host }} "

  - name: containers
    rules:
      - alert: UnhealthyContainers
        expr: 'netdata_docker_containers_health_status_containers_average{dimension="unhealthy"} > 0.3'
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Unhealthy Containers on {{ $labels.host }}"
          description: "{{ $value }} containers are not healthy on host {{ $labels.host }}"

  - name: smart
    interval: 10m # evaluate these queries with reduced frequency
    rules:
      - alert: SMARTUncorrectableSectors
        expr: increase(netdata_smartctl_device_smart_attr_offline_uncorrectable_sectors_average [1d]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Uncorrectable Sectors on {{ $labels.host }}"
          description: "SMART Wear: {{ $value }} new offline uncorrectable sectors in the last day on {{ $labels.host }}, disk {{ $labels.dimension }}"

      - alert: SMARTReallocatedSectors
        expr: increase(netdata_smartctl_device_smart_attr_reallocated_sector_ct_sectors_average [1d]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Reallocated Sectors on {{ $labels.host }}"
          description: "SMART Wear: {{ $value }} new reallocated sectors in the last day on {{ $labels.host }}, disk {{ $labels.dimension }}"

      - alert: SMARTPendingSectors
        expr: netdata_smartctl_device_smart_attr_current_pending_sector_sectors_average > 0
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "Pending Sectors on {{ $labels.host }}"
          description: "SMART Wear: {{ $value }} current pending sectors on {{ $labels.host }}, disk {{ $labels.dimension }}"

      - alert: SMARTCrCErrors
        expr: increase(netdata_smartctl_device_smart_attr_udma_crc_error_count_errors_average [1d]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "CRC ERRORS on {{ $labels.host }}"
          description: "SMART Wear: {{ $value | humanize }} CRC errors increase in the last day  on {{ $labels.host }}, disk {{ $labels.dimension }}"

      - alert: SMARTReallocationEvents
        expr: increase(netdata_smartctl_device_smart_attr_reallocated_event_count_events_average [1h]) > 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Reallocation Events {{ $labels.host }}"
          description: "SMART Wear: {{ $value }} Reallocation Events on {{ $labels.host }}, disk {{ $labels.dimension }}"
