---
# {{ ansible_managed }}

services:
  youtrack:
    image: jetbrains/youtrack:{{ youtrack_version }}
    volumes:
      - ./data:/opt/youtrack/data
      - ./conf:/opt/youtrack/conf
      - ./logs:/opt/youtrack/logs
      - ./backups:/opt/youtrack/backups
    environment:
      VIRTUAL_HOST: {{ youtrack_domain }}
      LETSENCRYPT_HOST: {{ youtrack_domain }}
      LETSENCRYPT_EMAIL: {{ letsencrypt_email }}
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - webproxy
    deploy:
      resources:
        limits:
          memory: {{ youtrack_container_memory_limit }}
        reservations:
          memory: {{ youtrack_container_memory_reservation }}
    healthcheck:
      test: ["CMD", "curl", "-s", "--head", "--fail", "http://localhost:8080/hub/auth/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  webproxy:
    external: true
    name: webproxy
