---
# defaults file for webproxy

webproxy_path: '/container/webproxy'

# set access_log off; in nginx
webproxy_access_log_off: false

# custom nginx config (http section) added to custom_options.conf in conf.d/
webproxy_nginx_custom_options:
# custom config for default location (included in every generated location)
webproxy_default_location_custom:

# custom config for default vhost (included in every generated server block)
webproxy_default_vhost_custom:

# pull docker images (docker compose pull)
webproxy_docker_pull: '{{ global_docker_pull | default(False) }}'

webproxy_cookies_secure_only: false

webproxy_nginx_worker_connections: 8096

## Default server configuration
# Domain of server to receive requests for unconfigured domains
# Needs to be configured as first domain in VIRTUAL_HOST= for a service
webproxy_default_host: ""

# Proxy Timeout options
# https://nginx.org/en/docs/http/ngx_http_proxy_module.html
webproxy_proxy_read_timeout: 60s
webproxy_proxy_connect_timeout: 60s
webproxy_proxy_send_timeout: 60s


webproxy_nginx_image: nginx:alpine
webproxy_dockergen_image: nginxproxy/docker-gen:latest
webproxy_letsencrypt_image: nginxproxy/acme-companion:latest

webproxy_letsencrypt_default_email: '{{ letsencrypt_email }}'

webproxy_nginx_tmpl_file: nginx.tmpl

# list of additional external networks
webproxy_additional_networks: []
webproxy_ignore_missing_network: true

# content of /.well-known/security.txt
# See https://securitytxt.org/
webproxy_security_txt:
# webproxy_security_txt: |
#   # Our security address
#   Contact: mailto:security@example.com
