---

services:
  nginx:
    image: '{{ tileserver_nginx_image }}'
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: "{{ tileserver_domain }}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "{{ tileserver_domain }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt_email }}"
    volumes:
      # - ./htaccess:/etc/nginx/conf.d/htaccess:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/maps:/etc/nginx/maps:ro
      - ./nginx/cache:/cache
    networks:
      tileserver:
      webproxy:
    depends_on:
      - tileserver
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --head --silent --output /dev/null http://localhost:80/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  tileserver:
    image: "{{ tileserver_image }}"
    restart: always
    volumes:
      - type: bind
        source: '{{ tileserver_data_path }}'
        target: /data
        read_only: false
    expose:
      - 8080
    command: --config /data/config.json --silent # --verbose
    networks:
      - tileserver
    healthcheck:
      test: ["CMD-SHELL", "node -e 'http.get(\"http://localhost:8080/health\", (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on(\"error\", () => process.exit(1))'"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  tileserver:
    driver: bridge
  webproxy:
    external: true
    name: webproxy
