---
# Vector configuration

- name: include vector config
  import_tasks: vector.yml
  when: vector_service_enabled

- name: Disable Vector Service
  systemd:
    name: vector
    enabled: false
    state: stopped
    masked: true
  when: not vector_service_enabled
