---
# See available releases: https://github.com/pdf/zfs_exporter/releases/
zfs_exporter_version: '2.3.4'
zfs_exporter_arch: 'amd64'
zfs_exporter_download_url: https://github.com/pdf/zfs_exporter/releases/download/v{{ zfs_exporter_version }}/zfs_exporter-{{ zfs_exporter_version }}.linux-{{ zfs_exporter_arch }}.tar.gz

zfs_exporter_bin_path: /usr/local/bin/zfs_exporter

zfs_exporter_options: >
  --web.listen-address 127.0.0.1:9134
  --properties.dataset-filesystem="available,logicalused,quota,referenced,used,usedbydataset,written,logicalreferenced,usedbysnapshots,usedbychildren,compressratio"
  --exclude='/docker'
  --deadline=8s

zfs_exporter_state: started
zfs_exporter_enabled: true

zfs_exporter_scrape_config_deploy: false
zfs_exporter_scrape_config_dir: "{{ vmagent_scrape_config_dir | default('/opt/vic-vmagent/scrape_configs') }}"
zfs_exporter_metrics_scraper_service: vic-vmagent
