---
# defaults file for zammad
zammad_path: '/container/zammad'
zammad_domain: 'zammad.{{ ansible_fqdn }}'
zammad_letsencrypt_host: '{{ zammad_domain }}'

# Version as on docker hub: https://hub.docker.com/r/zammad/zammad-docker-compose/tags
zammad_version: latest # 6.0.0-95
zammad_elasticsearch_version: 8.8.0
zammad_memcache_version: 1.6.20-alpine
zammad_redis_version: 7.2.3-alpine
zammad_postgres_version: 15.3-alpine

# to be replaced in host_vars
zammad_postgres_user: zammad
# zammad_postgres_pass:

zammad_backup_time: "03:00"
zammad_backup_timezone: "Etc/UTC"
zammad_backup_hold_days: 10

# set to true, to skip archiving file storage (./data/zammad-storage)
zammad_backup_no_file_backup: false

# pull docker images (docker compose pull)
zammad_docker_pull: '{{ global_docker_pull | default(False) }}'

# rebuild elasticsearch index on every fresh start
# for big installations it can take more than 1h (27'000 Tickets)
# alternative: reindex manually:
# docker compose exec zammad-railsserver rake zammad:searchindex:rebuild
zammad_elasticsearch_reindex: true

# expose elasticsearch readonly through webproxy (for Grafana integration)
zammad_elasticsearch_expose: false
# zammad_elasticsearch_htpasswd:
zammad_elasticsearch_domain: 'es.{{ zammad_domain }}'

zammad_webproxy_path: '{{ webproxy_path | default("/container/webproxy") }}'

# Elasticsearch RAM allocation (Java Xms, Xmx). valid format: 512m, 2g
# default: 40% of total memory
zammad_elasticsearch_memory: '{{ (ansible_memtotal_mb * 0.4) | round | int }}m'

# customize knowledge base html template.
zammad_kb_html_custom: false
# zammad_kb_html:

zammad_env_custom: |
  # Custom .env variables
