---

services:
  nexus:
    image: sonatype/nexus3:{{ nexus_version }}
    volumes:
      - type: bind
        source: './data'
        target: /nexus-data
        read_only: false
    environment:
      VIRTUAL_HOST: {{ nexus_domain }}
      LETSENCRYPT_HOST: {{ nexus_domain }}
      LETSENCRYPT_EMAIL: {{ letsencrypt_email }}
{% if nexus_add_vm_params %}
      INSTALL4J_ADD_VM_PARAMS: {{ nexus_add_vm_params }}
{% endif %}
    restart: unless-stopped
    expose:
      - 8081
    networks:
      - webproxy
    healthcheck:
      test: ["CMD-SHELL", "curl --head --fail 127.0.0.1:8081/service/rest/v1/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  webproxy:
    external: true
    name: webproxy
