---

services:
  nexus:
    image: sonatype/nexus3:{{ nexus_version }}
    volumes:
      - type: bind
        source: './data'
        target: /nexus-data
        read_only: false
    environment:
      VIRTUAL_HOST: {{ nexus_domain }}
      LETSENCRYPT_HOST: {{ nexus_domain }}
      LETSENCRYPT_EMAIL: {{ letsencrypt_email }}
{% if nexus_add_vm_params %}
      INSTALL4J_ADD_VM_PARAMS: {{ nexus_add_vm_params }}
{% endif %}
    restart: unless-stopped
    expose:
      - 8081
    networks:
      - webproxy

networks:
  webproxy:
    external: true
    name: webproxy
