---
# https://hub.docker.com/r/victoriametrics/vmagent/tags?page=1&ordering=last_updated
victoriametrics_version: latest
victoriametrics_vmagent_version: '{{ victoriametrics_version }}'
victoriametrics_vmalert_version: '{{ victoriametrics_version }}'

victoriametrics_domain: 'metrics.{{ ansible_fqdn }}'

victoriametrics_nginx_image: nginx:alpine

# retention period (months) https://victoriametrics.github.io/#retention
victoriametrics_retention_period: 3
victoriametrics_big_merge_concurrency: 0
victoriametrics_max_samples_per_query: 1000000000
victoriametrics_max_unique_timeseries: 0 # 0 = auto (max 300000?)

victoriametrics_path: '/container/victoriametrics'
victoriametrics_docker_pull: '{{ global_docker_pull | default(False) }}'

# storage path for metrics data
victoriametrics_storage_path: '{{ victoriametrics_path }}/vmdata'

victoriametrics_htpasswd_read:
victoriametrics_htpasswd_write:
victoriametrics_htpasswd_admin:

victoriametrics_alertmanager_address: alertmanager.example.com
victoriametrics_alertmanager_port: 443
victoriametrics_alertmanager_scheme: https
victoriametrics_alertmanager_url: '{{ victoriametrics_alertmanager_scheme }}://{{ victoriametrics_alertmanager_address }}:{{ victoriametrics_alertmanager_port }}/'
victoriametrics_alertmanager_user: ''
victoriametrics_alertmanager_password: ''

victoriametrics_scrape_interval: 10s
victoriametrics_scrape_timeout: 10s
victoriametrics_http_scrape_interval: 1m

# Alertmanager source can link to graph in grafana.
victoriametrics_grafana_datasource_name: VictoriaMetrics
victoriametrics_vmalert_evaluation_interval: 1m
victoriametrics_vmalert_external_url: 'https://grafana.yourdomain.com'
victoriametrics_vmalert_external_source: explore?orgId=1&left={"datasource":"{{ victoriametrics_grafana_datasource_name }}","queries":[{"expr":{% raw %}{{.Expr|jsonEscape|queryEscape}}{% endraw %},"refId":"A"}],"range":{"from":"now-24h","to":"now"}}

# external labels added to all alerts. To see and filter in alertmanager where the alert is coming from
victoriametrics_vmalert_external_labels:
  - 'alertsource={{ victoriametrics_domain }}'

victoriametrics_blackbox_image: prom/blackbox-exporter
victoriametrics_blackbox_version: master # if unstable v0.18.0 can be used

victoriametrics_blackbox_log_level: info # Only log messages with the given severity or above. One of: [debug, info, warn, error]
victoriametrics_blackbox_prober_log_level: warn # Log level from probe requests. One of: [debug, info, warn, error, none]

# define your targets, creates files in file_sd/<name>.<job>.yml
victoriametrics_file_sd_config: []
  # - job: http_2xx
  #   name: production
  #   config:
  #     - labels:
  #         environment: production
  #       targets:
  #         - https://example.com/

# additional blackbox_exporter modules
victoriametrics_blackbox_modules: {}

victoriametrics_scrape_configs: []

victoriametrics_oauth2_proxy_integration: false
victoriametrics_oauth2_proxy_host: oauth2-proxy.{{ victoriametrics_domain }}
victoriametrics_oauth2_proxy_internal_host: true
victoriametrics_oauth2_proxy_cookie_name: "_oauth2_{{ victoriametrics_domain }}"
