- name: youtrack_directories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - '{{ youtrack_path }}'

- name: youtrack data directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '13001' # youtrack inside container
    group: '13001' # youtrack inside container
    mode: '0755'
  with_items:
    - '{{ youtrack_path }}/data'
    - '{{ youtrack_path }}/conf'
    - '{{ youtrack_path }}/logs'
    - '{{ youtrack_path }}/backups'

- name: deploy config
  template:
    src: 'docker-compose.yml'
    dest: '{{ youtrack_path }}/docker-compose.yml'
    owner: root
    group: root
    mode: '0644'

- name: deploy youtrack.jvmoptions
  template:
    src: 'youtrack.jvmoptions.j2'
    dest: '{{ youtrack_path }}/conf/youtrack.jvmoptions'
    owner: '13001' # youtrack inside container
    group: '13001' # youtrack inside container
    mode: '0644'
  notify: youtrack_restart

- name: proxy config tuning
  template:
    src: nginx-proxy-config.conf
    dest: '{{ youtrack_webproxy_path }}/data/vhost.d/{{ youtrack_domain }}'
    owner: root
    group: root
    mode: '0644'
  notify:
    - youtrack_webproxy_nginx_restart

- name: youtrack_docker-compose-up
  community.docker.docker_compose_v2:
    project_src: '{{ youtrack_path }}'
    state: present
  register: youtrack__register_compose
  tags: compose_up

- name: print actions by compose # noqa no-handler
  vars:
    actions: "{{ youtrack__register_compose.actions }}"
  debug:
    var: actions
  changed_when: true
  when: youtrack__register_compose is defined and youtrack__register_compose.changed
