---
# handlers file for nextcloud


- name: nextcloud_docker-compose-build
  community.docker.docker_compose_v2:
    project_src: '{{ nextcloud_path }}'
    state: present
    build: always
    pull: always

- name: nextcloud_docker-compose-restart
  community.docker.docker_compose_v2:
    project_src: '{{ nextcloud_path }}'
    state: restarted

- name: nextcloud_webproxy_nginx_restart
  community.docker.docker_compose_v2:
    project_src: '{{ nextcloud_webproxy_path }}'
    services:
      - nginx
    state: restarted
