---
# defaults file for loki deployment
loki_path: '/container/loki'

# loki_domain: '{{ ansible_fqdn }}'
loki_domain: "loki.{{ ansible_fqdn }}"
loki_version: 3.0.0

# htpasswd -B -n username
loki_htpasswd: |
  testuser:$2y$05$5RJ/ieXn7XpXM7R97IZKEOfFLWEo3B0W1KGNQKuArAg3Bt7E9o8Qa

loki_htpasswd_push_only: |
  testuser:$2y$05$5RJ/ieXn7XpXM7R97IZKEOfFLWEo3B0W1KGNQKuArAg3Bt7E9o8Qa

loki_docker_pull: '{{ global_docker_pull | default(False) }}'

loki_alertmanager_url: "" # http://alertmanager:9093
loki_alertmanager_username: loki
loki_alertmanager_password:

loki_push_access_log: false

# authentication by subrequest for push_only
loki_auth: basic # basic/request

# for loki_auth: request
loki_auth_request_domain: # validator.example.com (domainwithout https://, it will use HTTPS)
loki_auth_request_location: # /api/logserveraccess
loki_auth_request_cache_time: 15m
loki_auth_request_cache_time_403: 30s

loki_nginx_image: nginx:alpine
loki_nginx_gateway_conf_template: '{{ "auth_basic-site.conf" if loki_auth == "basic" else "auth_request-site.conf" }}'

loki_rules: []

loki_storage_boltdb_shipper_cache_ttl: 24h  # Can be increased for faster performance over longer query periods, uses more disk space
loki_limits_max_query_lookback: 90d
loki_table_manager_retention_period: 91d # needs to be bigger than look back period

loki_limits_ingestion_rate_mb: 4 # int in MB, no unit
loki_limits_ingestion_burst_size_mb: 6 # int in MB, no unit
loki_limits_per_stream_rate_limit: 3MB # unit required
loki_limits_per_stream_rate_limit_burst: 15MB # unit required
loki_limits_max_query_length: 730h # 30d
loki_limits_retention_period: 91d # needs to be bigger than look back period

loki_max_message_size: 33554432
loki_log_level: info # Supported values [debug, info, warn, error]

# deploy scrape config file for scraping loki metrics with vmagent on host
loki_monitoring_integration: false
loki_host_port_bind_to: 127.0.0.1:3100
loki_vmagent_scrape_config_dir: "{{ vmagent_scrape_config_dir | default('/opt/vic-vmagent/scrape_configs') }}"

# metrics remotewrite (for recording rules)
loki_ruler_remote_write_enabled: false
loki_ruler_remote_write_url: "{{ vmagent_remotewrite_url }}"
loki_ruler_remote_write_username: '{{ vmagent_remotewrite_username }}'
loki_ruler_remote_write_password: '{{ vmagent_remotewrite_password }}'

loki_schema_v12_from: '2022-04-27'
loki_schema_tsdb_from: '2023-08-01'
loki_schema_tsdb_v13_from: '2024-07-01'
