# use include_role to workaround issue with run_once.
# a task with run_once is run on the first host in a play,
# if the run_once task is skipped because the role has a condition, then, the task will never run.
- name: import cloudalchemy.node_exporter
  include_role:
    name: cloudalchemy.node_exporter
    apply:
      tags:
        - node_exporter
        - node
  tags:
    - node_exporter
    - node

- name: Deploy Scrape Config File
  template:
    src: node_exporter_scrape_config.yml.j2
    dest: '{{ node_exporter_scrape_config_dir }}/node_exporter.yml'
    owner: root
    group: root
    mode: '0644'
  notify: node_exporter_metrics_scraper_service_reload
  when:
    - node_exporter_vmagent_integration | default(True)
  tags:
    - node_exporter
    - node

- name: Remove old vmagent integration file_sd_config
  file:
    path: /opt/vic-vmagent/file_sd_configs/local.node.yml
    state: absent
  tags:
    - node_exporter
    - node
