---

- name: import webserver role with vars for matomo
  import_role:
    name: teamapps.general.webserver
  vars:
    webserver_path: '{{ matomo_path }}'
    webserver_domain: '{{ matomo_domain }}'
    webserver_php_enable: true
    webserver_php_version: '{{ matomo_php_version }}'
    # additional packages for cli archiving
    # https://matomo.org/faq/troubleshooting/how-to-make-the-diagnostic-managing-processes-via-cli-to-display-ok/
    webserver_php_apt_packages:
      - gawk
      - procps
    webserver_php_extensions:
      - gd
      - intl
      - imagick
      - opcache
      - zip
      # - mcrypt
      - pdo_mysql
      - mysqli
      # - xdebug
      - soap
      - apcu
    webserver_mysql_enable: true
    webserver_mariadb_version: '{{ matomo_mariadb_version }}'
    webserver_mysql_root_password: '{{ matomo_mysql_root_password }}'
    webserver_mysql_database: '{{ matomo_mysql_database }}'
    webserver_mysql_user: '{{ matomo_mysql_user }}'
    webserver_mysql_password: '{{ matomo_mysql_password }}'
    webserver_document_root: matomo
    webserver_nginx_template: matomo-nginx.conf
  tags:
    - matomo

- name: matomo first install
  unarchive:
    remote_src: true
    src: https://builds.matomo.org/matomo.zip
    dest: '{{ matomo_path }}/code/'
    # mode: '0640'
    owner: www-data
    group: www-data
    creates: '{{ matomo_path }}/code/matomo/index.php'
  tags:
    - matomo

## if config file exists, the first-run setup does not work anymore. How to preconfigure database for installer?
# - name: copy initial config file
#   copy:
#     dest: '{{ matomo_path }}/code/matomo/config/config.ini.php'
#     content: |
#       ; <?php exit; ?> DO NOT REMOVE THIS LINE
#       ; file automatically generated or modified by Matomo; you can manually override the default values in global.ini.php by redefining them in this file.
#       [database]
#       host = "db"
#       username = "matomo"
#       password = "{{ matomo_mysql_password }}"
#       dbname = "matomo"
#       tables_prefix = "matomo_"
#       charset = "utf8mb4"
#     force: No
#     owner: www-data
#     group: www-data
#     mode: '0640'

# - name: config
#   ini_file:
#     path: '{{ matomo_path }}/code/matomo/config/config.ini.php'
#     section: database
#     option: '{{ item.key }}'
#     value: '{{ item.value }}'
#     create: No
#   with_dict:
#     host: db

- name: matomo console wrapper
  copy:
    content: |
      #!/bin/bash
      set -eu
      dir="$(dirname $(readlink -f $0))"
      cd $dir
      if [ -t 0 ] ; then
        tty=""
      else
        tty="-T"
      fi
      docker compose exec ${tty} -u www-data php matomo/console "$@"
    dest: '{{ matomo_path }}/matomo-console.sh'
    owner: root
    group: root
    mode: '0750'
  tags:
    - matomo

- name: setup a cronjob for matomo archiving
  cron:
    name: matomo
    minute: "*/10"
    hour: "*"
    user: root
    job: '{{ matomo_path }}/matomo-console.sh core:archive --concurrent-requests-per-website=3 -vvv > /var/log/matomo-archive.log'
    cron_file: matomo
  tags:
    - matomo
