---
# handlers file for netdata

- name: netdata_restart
  systemd:
    service: netdata
    state: restarted

- name: netdata_docker-compose-restart
  community.docker.docker_compose_v2:
    project_src: '{{ netdata_path }}'
    state: restarted
  tags: compose_up

- name: netdata_reload_alarms # noqa no-changed-when
  command: pkill -SIGUSR2 netdata

- name: netdata-smartd-restart
  systemd:
    service: smartd
    state: restarted
  notify: netdata_restart
