loki_canary_container_name: loki-canary.{{ ansible_fqdn }} # needs to be unique!
loki_canary_loki_domain: loki.example.com # websocket connection with tls on 443.
loki_canary_version: latest
loki_canary_user:
loki_canary_pass:
loki_canary_path: /container/loki-canary

loki_canary_port_bind_to: 127.0.0.1:3500

loki_canary_monitoring_integration: true
loki_canary_vmagent_scrape_config_dir: "{{ vmagent_scrape_config_dir | default('/opt/vic-vmagent/scrape_configs') }}"

loki_canary_docker_pull: '{{ global_docker_pull | default(False) }}'
