---
# defaults file for netdata
netdata_path: '/container/netdata'
netdata_domain: 'netdata.{{ ansible_fqdn }}'
netdata_htpasswd: ''

netdata_streaming_enabled: false
netdata_streaming_destination:
netdata_streaming_api_key:
netdata_streaming_skip_certificate_verification: false

# pull docker images (docker compose pull)
netdata_docker_pull: '{{ global_docker_pull | default(False) }}'

# Set to true for your hosts with docker and webproxy
netdata_docker_integration: false

# when not using docker_integration
netdata_bind_to: '127.0.0.1:19999'

# Set to false if you don't want to install/manage netdata on a host/group
netdata_manage_netdata: true

netdata_alarm_send_email: false
netdata_alarm_send_slack: false
netdata_alarm_send_custom: false

netdata_alarm_email_default_recipient: root@localhost
netdata_alarm_email_sender: "'Netdata on host {{ ansible_fqdn }}' <netdata@localhost>"

# Slack (Legacy) Webhooks: https://api.slack.com/legacy/custom-integrations/messaging/webhooks
netdata_alarm_slack_webhook_url: # https://hooks.slack.com/services/...
netdata_alarm_slack_recipients: '#' # use channel configured on webhook.

netdata_alarm_custom_recipient: "default"
netdata_alarm_custom_api_key: ""
netdata_alarm_custom_webhook: ""

netdata_cloud_enabled: false
netdata_cloud_base_url: https://app.netdata.cloud

# Disable all telemetry, including posthog in the frontend.
netdata_disable_telemetry: false

netdata_smartd_enabled: '{{ ansible_virtualization_role in ["host", "NA"] }}'

netdata_postgres_enabled: false
netdata_postgres_update_every: 1
netdata_postgres_autodetection_retry: 0
netdata_postgres_jobs: []

## Example:
# netdata_postgres_jobs:
#  - name: postgres_local
#    dsn: 'postgres://postgres:password@127.0.0.1:5432/postgres' # gitleaks:allow

# ~82.4M / 1000 metrics for a full day of per second retention.
# a server has 3000-6000 metrics.
# get the number of metrics: curl -s 'http://localhost:19999/api/v1/allmetrics?format=prometheus' | wc -l
# for 6000 metrics and ~1 day retention: 82.4M*6 = 495 M
netdata_dbengine_disk_space_mb_tier0: 256 # 1 point every second, ~82.4 MiB for 1000 metrics for a full day
netdata_dbengine_disk_space_mb_tier1: 128 # 1 point every minute, 4 bytes per point per point ~ 5.5 MiB per 1000 metrics per DAY.
netdata_dbengine_disk_space_mb_tier2: 64  # 1 point every hour, 4 bytes per point, ~ 0.64 MiB per 1000 metrics per WEEK.

netdata_dbengine_page_cache_size_mb: 64

netdata_webproxy_path: '{{ webproxy_path | default("/container/webproxy") }}'
