---
webserver_webproxy_path: '{{ webproxy_path | default("/container/webproxy") }}'

webserver_path: '/container/webserver'

webserver_domain: '{{ ansible_fqdn }}'
webserver_addon_domains: []

webserver_domains: '{{ [webserver_domain] + webserver_addon_domains }}'

webserver_document_root: httpdocs
webserver_nginx_image: nginxinc/nginx-unprivileged:stable-alpine
webserver_nginx_template: site.conf
webserver_client_max_body_size: 10M

# pull docker images (docker compose pull)
webserver_docker_pull: '{{ global_docker_pull | default(False) }}' # False = policy, True = always

webserver_php_enable: false
# custom php override config
webserver_php_override_custom: ''
webserver_php_image: '' # if set, use image from registry, else build image
webserver_php_version: '8'
webserver_php_memory_limit: 4G
webserver_php_apt_packages: []
  # - git
webserver_php_extensions:
  - gd
  - intl
  - imagick
  - opcache
  - zip
  # - mcrypt
  - pdo_mysql
  - mysqli
  # - xdebug
  # - soap
  - apcu
webserver_sftp_enable: false
webserver_sftp_port: 2222
webserver_sftp_authorized_keys: ''

webserver_mysql_enable: false
webserver_mariadb_version: latest
# webserver_mysql_root_password:
# webserver_mysql_database:
# webserver_mysql_user:
# webserver_mysql_password:

webserver_basic_auth: ''

# PhpMyAdmin interface on /.myadmin
webserver_myadmin_enable: false
# htpasswd file content (if webserver_basic_auth is used, it should also contain the myadmin_htpasswd credentials)
webserver_myadmin_htpasswd: ''
webserver_myadmin_absolute_uri: https://{{ webserver_domain }}/.myadmin/
webserver_myadmin_image: phpmyadmin:latest
webserver_myadmin_max_upload_size: 200M

# manage robots.txt
webserver_manage_robots_txt: false
# robots.txt is deleted when set to emtpty string ""
webserver_robots_txt: |
  User-agent: *
  Disallow: /
