---
# configure auth using webproxy

- name: create htpasswd file
  copy:
    content: '{{ prometheus_htpasswd }}' # to be changed if prometheus specific htpasswd is created
    dest: '{{ prometheus_webproxy_path }}/data/htpasswd/{{ prometheus_domain }}'
    owner: root
    group: root
    mode: '0644'
...
