---
services:

  nginx-gateway:
    image: '{{ loki_nginx_image }}'
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: {{ loki_domain }}
      LETSENCRYPT_HOST: {{ loki_domain }}
      LETSENCRYPT_EMAIL: {{ letsencrypt_email }}
    volumes:
      - ./htaccess:/etc/nginx/conf.d/htaccess:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      loki:
      webproxy:
        aliases:
          - loki-gateway-webproxy # used in grafana for direct connection to datasource
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --head --silent --output /dev/null http://localhost:80/proxystatus || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  loki:
    image: grafana/loki:{{ loki_version }}
    restart: always
    expose:
      - 3100
    ports:
      - "{{ loki_host_port_bind_to }}:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml:ro
      - ./data/loki:/data/loki
    command: -config.file=/etc/loki/config.yml
    networks:
      - loki
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    healthcheck:
      test: ["CMD", "wget", "-qO/dev/null", "http://127.0.0.1:3100/ready"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  loki:
  webproxy:
    external: true
    name: webproxy
