---
- name: create configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - "{{ victoriametrics_path }}"
    - "{{ victoriametrics_storage_path }}"

- name: deploy docker-compose.yml
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ victoriametrics_path }}/docker-compose.yml'
    owner: root
    group: root
    mode: '0640'

- name: include vmagent scraper config
  import_tasks: vmagent.yml

- name: include blackbox exporter config
  import_tasks: blackbox_exporter.yml

- name: include alerts config
  import_tasks: vmalert.yml

- name: include authproxy config
  import_tasks: authproxy.yml

- name: victoriametrics_docker-compose-up
  community.docker.docker_compose_v2:
    project_src: '{{ victoriametrics_path }}'
    state: present
    remove_orphans: true
    pull: "{{ victoriametrics_docker_pull | ternary('always', 'policy') }}"
  register: victoriametrics__register_compose
  tags: compose_up

- name: print actions by compose # noqa no-handler
  vars:
    actions: "{{ victoriametrics__register_compose.actions }}"
  debug:
    var: actions
  changed_when: true
  when: victoriametrics__register_compose is defined and victoriametrics__register_compose.changed
