---
- name: create file_sd directory
  file:
    path: "{{ victoriametrics_path }}/file_sd"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: create scrape_configs directory
  file:
    path: "{{ victoriametrics_path }}/scrape_configs"
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: create file discovery configuration
  copy:
    content: |
      #
      # Managed by ansible
      #
      {{ item.config | to_nice_yaml(indent=2) }}
    dest: "{{ victoriametrics_path }}/file_sd/{{ item.name | default('custom') }}.{{ item.job }}.yml"
    owner: root
    group: root
    mode: '0640'
  loop: '{{ victoriametrics_file_sd_config }}'

- name: deploy vmagent config file prometheus.yml
  template:
    src: 'prometheus.yml.j2'
    dest: '{{ victoriametrics_path }}/prometheus.yml'
    owner: root
    group: root
    mode: '0640'
  notify: victoriametrics-vmagent-restart

# validation in the template won't work because %s expansion won't be reachable from within the container
- name: vmagent validate config
  command: 'docker compose run --rm -T vmagent -dryRun -promscrape.config=/etc/prometheus/prometheus.yml -remoteWrite.url=http://victoriametrics:8428/api/v1/write'
  args:
    chdir: "{{ victoriametrics_path }}" # to run docker compose in the correct directory
  changed_when: false
