---


- name: create rules directory
  file:
    path: "{{ victoriametrics_path }}/rules"
    state: directory
    owner: root
    group: root
    mode: '0755'

# https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/README.md#alerts
- name: alerting rules file
  template:
    src: "rules/{{ item }}.j2"
    dest: "{{ victoriametrics_path }}/rules/{{ item }}"
    owner: root
    group: root
    mode: '0640'
  with_items:
    - alerts-health.yml
    - alerts-vmagent.yml
    - alerts-vmalert.yml
    - alerts-vmsingle.yml
  notify:
    - vmalert reload
    - vmalert validate config

- name: delete old rules
  file:
    path:
    dest: "{{ victoriametrics_path }}/rules/vmalert.rules.yml"
    state: absent

- name: copy alerting rule files
  copy:
    src: "{{ item }}"
    dest: "{{ victoriametrics_path }}/rules/"
    owner: root
    group: root
    mode: '0640'
  with_fileglob:
    - "rules/*.rules.yml"
  notify:
    - vmalert reload
    - vmalert validate config

# validation in the template won't work because %s expansion won't be reachable from within the container
- name: vmalert validate config
  command: docker compose run --rm -T vmalert -dryRun -rule=/etc/alerts/*.yml
  args:
    chdir: "{{ victoriametrics_path }}" # to run docker compose in the correct directory
  changed_when: false
...
