---
# tasks file for backuppcclient

- name: configure backuppc client
  import_tasks: backupclient.yml
  when: backuppcclient_manage
  tags:
    - backuppcclient

# create prebackupscript always
- name: create prebackup.sh script
  copy:
    content: "#!/bin/bash\nset -exu"
    dest: /usr/local/bin/prebackup.sh
    force: false
    owner: root
    group: root
    mode: '0750'
  tags:
    - backuppcclient
    - backuppcclient_local

# create postbackupscript always
- name: create postbackup.sh script
  copy:
    content: "#!/bin/bash\nset -exu"
    dest: /usr/local/bin/postbackup.sh
    force: false
    owner: root
    group: root
    mode: '0750'
  tags:
    - backuppcclient
    - backuppcclient_local
