---
# handlers file for webproxy

- name: webproxy_nginx_reload # noqa no-changed-when
  command: 'docker compose exec -T nginx nginx -s reload'
  args:
    chdir: '{{ webproxy_path }}'
  tags: compose_up

- name: webproxy_generator_restart
  community.docker.docker_compose_v2:
    project_src: '{{ webproxy_path }}'
    services:
      - docker-gen
    state: restarted
  tags: compose_up

- name: webproxy_docker-compose-restart
  community.docker.docker_compose_v2:
    project_src: '{{ webproxy_path }}'
    state: restarted
  tags: compose_up
