---

- name: create kimai directory
  file:
    path: '{{ kimai_path }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: create kimai/code directory
  file:
    path: '{{ kimai_path }}/code'
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: install git
  apt:
    name: git
    state: present

- name: deploy kimai source code
  become: true
  become_user: www-data
  git:
    repo: 'https://github.com/kevinpapst/kimai2.git'
    dest: '{{ kimai_path }}/code'
    version: '{{ kimai_version }}'
    depth: '1'
    force: true # symphony.lock is changed by composer install
  notify: kimai_update

- name: kimai docker compose override
  template:
    src: docker-compose.override.yml
    dest: '{{ kimai_path }}/docker-compose.override.yml'
    owner: 'root'
    group: 'root'
    mode: 0750

- name: import webserver role with vars for kimai
  import_role:
    name: teamapps.general.webserver
  vars:
    webserver_path: '{{ kimai_path }}'
    webserver_domain: '{{ kimai_domain }}'
    webserver_php_enable: True
    webserver_mysql_enable: True
    webserver_php_version: '{{ kimai_php_version }}'
    webserver_php_extensions: '{{ kimai_php_extensions }}'
    webserver_mariadb_version: '{{ kimai_mariadb_version }}'
    webserver_mysql_root_password: '{{ kimai_mysql_root_password }}'
    webserver_mysql_database: '{{ kimai_mysql_database }}'
    webserver_mysql_user: '{{ kimai_mysql_user }}'
    webserver_mysql_password: '{{ kimai_mysql_password }}'
    webserver_document_root: public
    webserver_nginx_template: nginx-kimai-site.conf
  tags:
    - kimai

- name: download composer
  get_url:
    url: https://getcomposer.org/download/2.4.4/composer.phar
    checksum: sha256:c252c2a2219956f88089ffc242b42c8cb9300a368fd3890d63940e4fc9652345
    dest: '{{ kimai_path }}/composer.phar'
    owner: '33' # www-data
    group: '33'
    mode: '0750'
  tags:
    - kimai

- name: create bin directory
  file:
    path: '{{ kimai_path }}/bin'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: kimai console wrapper
  copy:
    content: |
      #!/bin/bash
      set -eux
      dir="$(dirname $(readlink -f $0))"
      cd $dir
      docker compose exec --user 33 php bin/console "$@"
    dest: '{{ kimai_path }}/bin/console'
    owner: root
    group: root
    mode: 0750

- name: kimai composer wrapper
  copy:
    content: |
      #!/bin/bash
      set -eux
      dir="$(dirname $(readlink -f $0))"
      cd $dir
      docker compose exec --user 33 php composer "$@"
    dest: '{{ kimai_path }}/bin/composer'
    owner: root
    group: root
    mode: 0750

- name: kimai .env
  template:
    src: kimai.env.j2
    dest: '{{ kimai_path }}/code/.env'
    owner: '33' # www-data
    group: '33'
    mode: 0750
  tags:
    - kimai

- name: kimai composer install
  command: 'docker compose run --rm --user 33 php /usr/local/bin/composer install --no-dev --optimize-autoloader'
  args:
    chdir: '{{ kimai_path }}'
    creates: '{{ kimai_path }}/code/vendor/autoload.php'
  notify:
    - kimai_update
